# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Server2Client.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Server2Client.proto',
  package='Server2Client',
  syntax='proto3',
  serialized_options=_b('\252\002\035Google.Protobuf.Server2Client'),
  serialized_pb=_b('\n\x13Server2Client.proto\x12\rServer2Client\"\x85\x01\n\x0bSightObject\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.Server2Client.ObjectType\x12\'\n\x04team\x18\x02 \x01(\x0e\x32\x19.Server2Client.ObjectTeam\x12$\n\x03pos\x18\x03 \x01(\x0b\x32\x17.Server2Client.Vector2D\"\xb5\x01\n\x0eSightCharacter\x12\'\n\x04team\x18\x01 \x01(\x0e\x32\x19.Server2Client.ObjectTeam\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x1c.Server2Client.CharacterType\x12$\n\x03pos\x18\x03 \x01(\x0b\x32\x17.Server2Client.Vector2D\x12(\n\x07\x66\x61\x63\x65\x44ir\x18\x04 \x01(\x0b\x32\x17.Server2Client.Vector2D\"q\n\tStateData\x12\x0e\n\x06health\x18\x01 \x01(\x05\x12$\n\x03pos\x18\x02 \x01(\x0b\x32\x17.Server2Client.Vector2D\x12.\n\rfaceDirVector\x18\x03 \x01(\x0b\x32\x17.Server2Client.Vector2D\"\xaf\x01\n\rCharacterData\x12\x0b\n\x03tag\x18\x01 \x01(\x05\x12\'\n\x05state\x18\x02 \x01(\x0b\x32\x18.Server2Client.StateData\x12\x30\n\x0csight_object\x18\x03 \x03(\x0b\x32\x1a.Server2Client.SightObject\x12\x36\n\x0fsight_character\x18\x04 \x03(\x0b\x32\x1d.Server2Client.SightCharacter\"U\n\tFrameData\x12\x33\n\rcharacterdata\x18\x01 \x03(\x0b\x32\x1c.Server2Client.CharacterData\x12\x13\n\x0b\x66ramenumber\x18\x02 \x01(\x05\"n\n\x08TurnData\x12+\n\tframedata\x18\x01 \x03(\x0b\x32\x18.Server2Client.FrameData\x12\x0c\n\x04turn\x18\x02 \x01(\x05\x12\x10\n\x08sendtime\x18\x03 \x01(\x03\x12\x15\n\rrecvlimittime\x18\x04 \x01(\x03\" \n\x08Vector2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02*G\n\rCharacterType\x12\t\n\x05\x44UMMY\x10\x00\x12\n\n\x06ROLLER\x10\x01\x12\n\n\x06TANKER\x10\x02\x12\n\n\x06HERMIT\x10\x03\x12\x07\n\x03ORB\x10\x04*U\n\nObjectType\x12\n\n\x06\x42ULLET\x10\x00\x12\x11\n\rOBSTACLE_WALL\x10\x02\x12\x12\n\x0eOBSTACLE_CRACK\x10\x03\x12\x14\n\x10OBSTACLE_FRAGILE\x10\x04*0\n\nObjectTeam\x12\x0b\n\x07NETURAL\x10\x00\x12\n\n\x06\x46RIEND\x10\x01\x12\t\n\x05\x45NEMY\x10\x02\x42 \xaa\x02\x1dGoogle.Protobuf.Server2Clientb\x06proto3')
)

_CHARACTERTYPE = _descriptor.EnumDescriptor(
  name='CharacterType',
  full_name='Server2Client.CharacterType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DUMMY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROLLER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TANKER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HERMIT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORB', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=884,
  serialized_end=955,
)
_sym_db.RegisterEnumDescriptor(_CHARACTERTYPE)

CharacterType = enum_type_wrapper.EnumTypeWrapper(_CHARACTERTYPE)
_OBJECTTYPE = _descriptor.EnumDescriptor(
  name='ObjectType',
  full_name='Server2Client.ObjectType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BULLET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OBSTACLE_WALL', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OBSTACLE_CRACK', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OBSTACLE_FRAGILE', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=957,
  serialized_end=1042,
)
_sym_db.RegisterEnumDescriptor(_OBJECTTYPE)

ObjectType = enum_type_wrapper.EnumTypeWrapper(_OBJECTTYPE)
_OBJECTTEAM = _descriptor.EnumDescriptor(
  name='ObjectTeam',
  full_name='Server2Client.ObjectTeam',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NETURAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRIEND', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENEMY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1044,
  serialized_end=1092,
)
_sym_db.RegisterEnumDescriptor(_OBJECTTEAM)

ObjectTeam = enum_type_wrapper.EnumTypeWrapper(_OBJECTTEAM)
DUMMY = 0
ROLLER = 1
TANKER = 2
HERMIT = 3
ORB = 4
BULLET = 0
OBSTACLE_WALL = 2
OBSTACLE_CRACK = 3
OBSTACLE_FRAGILE = 4
NETURAL = 0
FRIEND = 1
ENEMY = 2



_SIGHTOBJECT = _descriptor.Descriptor(
  name='SightObject',
  full_name='Server2Client.SightObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Server2Client.SightObject.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team', full_name='Server2Client.SightObject.team', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='Server2Client.SightObject.pos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=172,
)


_SIGHTCHARACTER = _descriptor.Descriptor(
  name='SightCharacter',
  full_name='Server2Client.SightCharacter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team', full_name='Server2Client.SightCharacter.team', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='Server2Client.SightCharacter.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='Server2Client.SightCharacter.pos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='faceDir', full_name='Server2Client.SightCharacter.faceDir', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=356,
)


_STATEDATA = _descriptor.Descriptor(
  name='StateData',
  full_name='Server2Client.StateData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='health', full_name='Server2Client.StateData.health', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='Server2Client.StateData.pos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='faceDirVector', full_name='Server2Client.StateData.faceDirVector', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=471,
)


_CHARACTERDATA = _descriptor.Descriptor(
  name='CharacterData',
  full_name='Server2Client.CharacterData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='Server2Client.CharacterData.tag', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='Server2Client.CharacterData.state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sight_object', full_name='Server2Client.CharacterData.sight_object', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sight_character', full_name='Server2Client.CharacterData.sight_character', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=649,
)


_FRAMEDATA = _descriptor.Descriptor(
  name='FrameData',
  full_name='Server2Client.FrameData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='characterdata', full_name='Server2Client.FrameData.characterdata', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='framenumber', full_name='Server2Client.FrameData.framenumber', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=651,
  serialized_end=736,
)


_TURNDATA = _descriptor.Descriptor(
  name='TurnData',
  full_name='Server2Client.TurnData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='framedata', full_name='Server2Client.TurnData.framedata', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turn', full_name='Server2Client.TurnData.turn', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sendtime', full_name='Server2Client.TurnData.sendtime', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recvlimittime', full_name='Server2Client.TurnData.recvlimittime', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=738,
  serialized_end=848,
)


_VECTOR2D = _descriptor.Descriptor(
  name='Vector2D',
  full_name='Server2Client.Vector2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Server2Client.Vector2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Server2Client.Vector2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=850,
  serialized_end=882,
)

_SIGHTOBJECT.fields_by_name['type'].enum_type = _OBJECTTYPE
_SIGHTOBJECT.fields_by_name['team'].enum_type = _OBJECTTEAM
_SIGHTOBJECT.fields_by_name['pos'].message_type = _VECTOR2D
_SIGHTCHARACTER.fields_by_name['team'].enum_type = _OBJECTTEAM
_SIGHTCHARACTER.fields_by_name['type'].enum_type = _CHARACTERTYPE
_SIGHTCHARACTER.fields_by_name['pos'].message_type = _VECTOR2D
_SIGHTCHARACTER.fields_by_name['faceDir'].message_type = _VECTOR2D
_STATEDATA.fields_by_name['pos'].message_type = _VECTOR2D
_STATEDATA.fields_by_name['faceDirVector'].message_type = _VECTOR2D
_CHARACTERDATA.fields_by_name['state'].message_type = _STATEDATA
_CHARACTERDATA.fields_by_name['sight_object'].message_type = _SIGHTOBJECT
_CHARACTERDATA.fields_by_name['sight_character'].message_type = _SIGHTCHARACTER
_FRAMEDATA.fields_by_name['characterdata'].message_type = _CHARACTERDATA
_TURNDATA.fields_by_name['framedata'].message_type = _FRAMEDATA
DESCRIPTOR.message_types_by_name['SightObject'] = _SIGHTOBJECT
DESCRIPTOR.message_types_by_name['SightCharacter'] = _SIGHTCHARACTER
DESCRIPTOR.message_types_by_name['StateData'] = _STATEDATA
DESCRIPTOR.message_types_by_name['CharacterData'] = _CHARACTERDATA
DESCRIPTOR.message_types_by_name['FrameData'] = _FRAMEDATA
DESCRIPTOR.message_types_by_name['TurnData'] = _TURNDATA
DESCRIPTOR.message_types_by_name['Vector2D'] = _VECTOR2D
DESCRIPTOR.enum_types_by_name['CharacterType'] = _CHARACTERTYPE
DESCRIPTOR.enum_types_by_name['ObjectType'] = _OBJECTTYPE
DESCRIPTOR.enum_types_by_name['ObjectTeam'] = _OBJECTTEAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SightObject = _reflection.GeneratedProtocolMessageType('SightObject', (_message.Message,), {
  'DESCRIPTOR' : _SIGHTOBJECT,
  '__module__' : 'Server2Client_pb2'
  # @@protoc_insertion_point(class_scope:Server2Client.SightObject)
  })
_sym_db.RegisterMessage(SightObject)

SightCharacter = _reflection.GeneratedProtocolMessageType('SightCharacter', (_message.Message,), {
  'DESCRIPTOR' : _SIGHTCHARACTER,
  '__module__' : 'Server2Client_pb2'
  # @@protoc_insertion_point(class_scope:Server2Client.SightCharacter)
  })
_sym_db.RegisterMessage(SightCharacter)

StateData = _reflection.GeneratedProtocolMessageType('StateData', (_message.Message,), {
  'DESCRIPTOR' : _STATEDATA,
  '__module__' : 'Server2Client_pb2'
  # @@protoc_insertion_point(class_scope:Server2Client.StateData)
  })
_sym_db.RegisterMessage(StateData)

CharacterData = _reflection.GeneratedProtocolMessageType('CharacterData', (_message.Message,), {
  'DESCRIPTOR' : _CHARACTERDATA,
  '__module__' : 'Server2Client_pb2'
  # @@protoc_insertion_point(class_scope:Server2Client.CharacterData)
  })
_sym_db.RegisterMessage(CharacterData)

FrameData = _reflection.GeneratedProtocolMessageType('FrameData', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEDATA,
  '__module__' : 'Server2Client_pb2'
  # @@protoc_insertion_point(class_scope:Server2Client.FrameData)
  })
_sym_db.RegisterMessage(FrameData)

TurnData = _reflection.GeneratedProtocolMessageType('TurnData', (_message.Message,), {
  'DESCRIPTOR' : _TURNDATA,
  '__module__' : 'Server2Client_pb2'
  # @@protoc_insertion_point(class_scope:Server2Client.TurnData)
  })
_sym_db.RegisterMessage(TurnData)

Vector2D = _reflection.GeneratedProtocolMessageType('Vector2D', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR2D,
  '__module__' : 'Server2Client_pb2'
  # @@protoc_insertion_point(class_scope:Server2Client.Vector2D)
  })
_sym_db.RegisterMessage(Vector2D)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
