# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Pick.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Pick.proto',
  package='PickData',
  syntax='proto3',
  serialized_options=_b('\252\002\030Google.Protobuf.PickData'),
  serialized_pb=_b('\n\nPick.proto\x12\x08PickData\"r\n\x04Pick\x12.\n\rBlueCharacter\x18\x01 \x03(\x0e\x32\x17.PickData.CharacterType\x12-\n\x0cRedCharacter\x18\x02 \x03(\x0e\x32\x17.PickData.CharacterType\x12\x0b\n\x03tag\x18\x03 \x01(\x05*V\n\rCharacterType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06ROLLER\x10\x01\x12\n\n\x06TANKER\x10\x02\x12\n\n\x06HERMIT\x10\x03\x12\x07\n\x03ORB\x10\x04\x12\x0b\n\x07PRIVATE\x10\x05\x42\x1b\xaa\x02\x18Google.Protobuf.PickDatab\x06proto3')
)

_CHARACTERTYPE = _descriptor.EnumDescriptor(
  name='CharacterType',
  full_name='PickData.CharacterType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROLLER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TANKER', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HERMIT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORB', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PRIVATE', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=140,
  serialized_end=226,
)
_sym_db.RegisterEnumDescriptor(_CHARACTERTYPE)

CharacterType = enum_type_wrapper.EnumTypeWrapper(_CHARACTERTYPE)
UNKNOWN = 0
ROLLER = 1
TANKER = 2
HERMIT = 3
ORB = 4
PRIVATE = 5



_PICK = _descriptor.Descriptor(
  name='Pick',
  full_name='PickData.Pick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BlueCharacter', full_name='PickData.Pick.BlueCharacter', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RedCharacter', full_name='PickData.Pick.RedCharacter', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='PickData.Pick.tag', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=138,
)

_PICK.fields_by_name['BlueCharacter'].enum_type = _CHARACTERTYPE
_PICK.fields_by_name['RedCharacter'].enum_type = _CHARACTERTYPE
DESCRIPTOR.message_types_by_name['Pick'] = _PICK
DESCRIPTOR.enum_types_by_name['CharacterType'] = _CHARACTERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pick = _reflection.GeneratedProtocolMessageType('Pick', (_message.Message,), {
  'DESCRIPTOR' : _PICK,
  '__module__' : 'Pick_pb2'
  # @@protoc_insertion_point(class_scope:PickData.Pick)
  })
_sym_db.RegisterMessage(Pick)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
