# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Client2Server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Client2Server.proto',
  package='Client2Server',
  syntax='proto3',
  serialized_options=_b('\252\002\035Google.Protobuf.Client2Server'),
  serialized_pb=_b('\n\x13\x43lient2Server.proto\x12\rClient2Server\" \n\x08Vector2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\x9d\x01\n\x10\x43haracterCommand\x12(\n\x07mov_dir\x18\x01 \x01(\x0b\x32\x17.Client2Server.Vector2D\x12\x14\n\x0crotate_speed\x18\x02 \x01(\x02\x12.\n\x0b\x66ocusaction\x18\x03 \x01(\x0e\x32\x19.Client2Server.ActionList\x12\x0b\n\x03tag\x18\x04 \x01(\x05\x12\x0c\n\x04turn\x18\x05 \x01(\x05\">\n\x07\x43ommand\x12\x33\n\ncommandata\x18\x01 \x03(\x0b\x32\x1f.Client2Server.CharacterCommand*=\n\nActionList\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06\x41TTACK\x10\x01\x12\x19\n\x15MAX_ACTION_DO_NOT_USE\x10\x03\x42 \xaa\x02\x1dGoogle.Protobuf.Client2Serverb\x06proto3')
)

_ACTIONLIST = _descriptor.EnumDescriptor(
  name='ActionList',
  full_name='Client2Server.ActionList',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATTACK', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAX_ACTION_DO_NOT_USE', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=296,
  serialized_end=357,
)
_sym_db.RegisterEnumDescriptor(_ACTIONLIST)

ActionList = enum_type_wrapper.EnumTypeWrapper(_ACTIONLIST)
NONE = 0
ATTACK = 1
MAX_ACTION_DO_NOT_USE = 3



_VECTOR2D = _descriptor.Descriptor(
  name='Vector2D',
  full_name='Client2Server.Vector2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Client2Server.Vector2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Client2Server.Vector2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=70,
)


_CHARACTERCOMMAND = _descriptor.Descriptor(
  name='CharacterCommand',
  full_name='Client2Server.CharacterCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mov_dir', full_name='Client2Server.CharacterCommand.mov_dir', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotate_speed', full_name='Client2Server.CharacterCommand.rotate_speed', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='focusaction', full_name='Client2Server.CharacterCommand.focusaction', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tag', full_name='Client2Server.CharacterCommand.tag', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turn', full_name='Client2Server.CharacterCommand.turn', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=230,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Client2Server.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commandata', full_name='Client2Server.Command.commandata', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=294,
)

_CHARACTERCOMMAND.fields_by_name['mov_dir'].message_type = _VECTOR2D
_CHARACTERCOMMAND.fields_by_name['focusaction'].enum_type = _ACTIONLIST
_COMMAND.fields_by_name['commandata'].message_type = _CHARACTERCOMMAND
DESCRIPTOR.message_types_by_name['Vector2D'] = _VECTOR2D
DESCRIPTOR.message_types_by_name['CharacterCommand'] = _CHARACTERCOMMAND
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.enum_types_by_name['ActionList'] = _ACTIONLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector2D = _reflection.GeneratedProtocolMessageType('Vector2D', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR2D,
  '__module__' : 'Client2Server_pb2'
  # @@protoc_insertion_point(class_scope:Client2Server.Vector2D)
  })
_sym_db.RegisterMessage(Vector2D)

CharacterCommand = _reflection.GeneratedProtocolMessageType('CharacterCommand', (_message.Message,), {
  'DESCRIPTOR' : _CHARACTERCOMMAND,
  '__module__' : 'Client2Server_pb2'
  # @@protoc_insertion_point(class_scope:Client2Server.CharacterCommand)
  })
_sym_db.RegisterMessage(CharacterCommand)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'Client2Server_pb2'
  # @@protoc_insertion_point(class_scope:Client2Server.Command)
  })
_sym_db.RegisterMessage(Command)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
